# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 28d33ee95a3d49eb81f5e30b8bfb7f1009759f83eda002adf1896d82654bb61e6bfd16baa5b77e8d01e988b86ca2c6e06643ea86eb21046ac651358af1870cee

test:
  secret_key_base: 5375b994a467ea2ce77d084349f1d26eff72a0d7f19f3ef9833a6988b4e772baf11d732221cd7e319185eafa05dc998573fd1f49effe394f61af49d356bd084a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
